name: firebase_example
description: A riverpod + Firebase + GoRouter integration example.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^7.1.1
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
